---
title: "TENTACLES"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{TENTACLES}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

##Data Loading

```{r setup}
# library(TENTACLES)
devtools::document()
devtools::load_all()

# Load data
df.count <- data("acc.count")
df.clin <- data("acc.clin")
```

##Pre-Processing

```{r preProcess}
# pre-Process data
a <- preProcess(df.count = df.count, df.clin = df.clin, batch = "patient.gender")
```

##Run Classifiers

```{r runClassifiers}
# Increase max size for parallel processing
options(future.globals.maxSize = 2 * 1024^3)
# Run classifiers
b <- runClassifiers(a, models = c("bag_mlp", "rand_forest", "mlp", "C5_rules"),
                    selector.recipes = c("boruta", "roc", "boruta", "boruta"), 
                    filter = TRUE, downsample = TRUE)
```

##Get Consensus genes

```{r getConsensus}
# Get and test consensus
c <- getConsensus(b, n.min = 4)
```

##Validate Consensus genes

```{r validation, message=FALSE, warning=TRUE}
# Import NEW data
count_table <- as.data.frame((b@data$adjusted.data))
gene_list <- c$consensusGenes
labels <- as.factor(b@data$metadata$class)

# Validation
d <- valConsensus(count_table, gene_list, labels, N = 10, metric = "FScore")
```

##Test Consensus genes

```{r, message=FALSE, warning=TRUE}
# Import NEW data
count_table <- as.data.frame((b@data$adjusted.data))
gene_list <- c$consensusGenes
labels <- as.factor(b@data$metadata$class)
# test consensus on an external dataset
e <- testConsensus(df.count = count_table, cons_genes = gene_list, class = labels)
```
